# -*- coding: utf-8 -*-
"""MON_TRAVAIL_DIRIGÉ_StrATer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uoYcL8J1F5Z2Wrx4cIwZlDrSh-LdEnnP
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt


from sklearn.impute import SimpleImputer
from statsmodels.formula.api import poisson
from statsmodels.formula.api import glm
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# importer la base de données
data = pd.read_excel('/content/Data_StrATer.xlsx')

# point global du nombre de ligne et de colonne.
print(data.shape)

# Liste du nom des colonnes.
print(data.keys())

# Categorisation par type variable

data_types = data.dtypes
numeric_columns = [col for col in data.columns if data[col].dtype in ['int64', 'float64']]
categorical_columns = [col for col in data.columns if data[col].dtype == 'object']

print("Variables numériques:", numeric_columns)
print("Variables catégoriques:", categorical_columns)

# Obtenir un résumé des valeurs manquantes dans chaque colonne
data.isnull().sum()

# Obtention de statistiques descriptives pour les variables numériques
data.describe().transpose()

# Obtention de statistiques descriptives pour les variables catégoriques
data.describe(include=['object']).transpose()

#Traittement des valeurs manquantes :: suppression des lignes pour toutes les variables manquantes

data.dropna(subset=numeric_columns, inplace=True)

# verification et control de correction par rapport aux valeurs manquantes
data.isnull().sum()

# point global du nombre de ligne et de colonne apres traitement des valeurs manquantes
print(data.shape)

# Transfornation de la varialle categorielle saison en variable binaire
data_mod=pd.get_dummies(data, columns=['Saison'])
data_mod

print(data_mod.keys())

# Tracé de la courbe du rendement Moy_ ZC025YR:
plt.figure(figsize=(10, 5))
plt.plot(data['Moy_ ZC025YR'], label='Moy_ ZC025YR')
plt.title('Graphique du rendement de obligations zero coupon de maturité 3 mois')
plt.xlabel('index')
plt.ylabel('Valeur')
plt.legend()
plt.grid(True)
plt.show()

# Tracé de la courbe du rendement Moy_ ZC050YR:
plt.figure(figsize=(10, 5))
plt.plot(data['Moy_ ZC050YR'], label='Moy_ ZC050YR')
plt.title('Graphique du rendement de obligations zero coupon de maturité 6 mois')
plt.xlabel('index')
plt.ylabel('Valeur')
plt.legend()
plt.grid(True)
plt.show()

# Tracé de la courbe du rendement Moy_ ZC075YR:
plt.figure(figsize=(10, 5))
plt.plot(data['Moy_ ZC075YR'], label='Moy_ ZC075YR')
plt.title('Graphique du rendement de obligations zero coupon de maturité 9 mois')
plt.xlabel('index')
plt.ylabel('Valeur')
plt.legend()
plt.grid(True)
plt.show()

# Tracé de la courbe du rendement Moy_ ZC100YR:
plt.figure(figsize=(10, 5))
plt.plot(data['Moy_ ZC100YR'], label='Moy_ ZC100YR')
plt.title('Graphique du rendement de obligations zero coupon de maturité 12 mois')
plt.xlabel('index')
plt.ylabel('Valeur')
plt.legend()
plt.grid(True)
plt.show()

"""### **On remarque clairement que les de rendement presentent des tendances**

### **REGRESSIONS LINEAIRES AVEC LA VARIABLE DEPENDANTE: Moy_ ZC025YR**
"""

# Sélection des variables indépendantes et de la variable dépendante
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'
X_2 = data_mod[['IAC_CAN']]

X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC025YR'] # utiliser aussi 'S&P_TSX_Der'

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

"""# Interpretation:
La régression linéaire ordinaire utilisée pour analyser l'influence des saisons et de l'Indice actuariel climatique (IAC_CAN) sur la variable, rendemeent des obligations de maturité 3 mois (**Moy_ZC025YR**) révèle des coefficients significatifs pour toutes les variables saisonnières, indiquant des augmentations pendant les différentes saisons par rapport à la moyenne annuelle, ainsi qu'un effet négatif significatif de l'Indice Actuariel Climatique Canadien . Cependant, le modèle n'explique que 11.9% de la variabilité de **Moy_ZC025YR**, suggérant que d'autres facteurs non inclus dans le modèle pourraient jouer un rôle.

Les diagnostics de résidus montrent une violation de la normalité, ce qui pourrait compromettre la fiabilité des estimations des coefficients. Pour améliorer le modèle, il serait pertinent d'explorer l'inclusion d'autres variables explicatives, d'appliquer des transformations pour améliorer la normalité des résidus, et d'envisager des modèles de volatilité ou des transformations de la variable dépendante pour mieux capturer la complexité des données. Des tests de robustesse pourraient également être réalisés pour évaluer la stabilité des coefficients à travers différentes spécifications du modèle. Ces améliorations aideraient à fournir des insights plus précis et à améliorer la compréhension des dynamiques influençant **Moy_ZC025YR**, crucial pour des applications pratiques telles que la planification financière et l'analyse des risques liés aux changements climatiques.
"""

# Sélection des variables indépendantes et de la variable dépendante en tenant compte des composantes de IAC
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'

X_2 = data_mod[['T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC','S_IAC']]
X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC025YR'] # utiliser aussi 'S&P_TSX_Der'

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

"""# Interpretation:
Les résultats de la régression ordinaire montrent que le modèle, bien que seulement capable de capturer 15.6% de la variabilité, identifie des liens significatifs entre les effets saisonniers et certains indicateurs climatiques avec les valeurs des rendements des obligations zero coupon de maturité 3 mois. Toutes les saisons présentent des coefficients positifs, soulignant un impact notable sur les valeurs moyennes comparativement à une ligne de base non spécifiée. Parmi les variables climatiques, les tempertures extrêmes basses (T10_IAC ) et le niveau de la mer (S_IAC) démontrent un impact significatif, indiquant une influence des conditions plus froides, tandis que P_IAC et D_IAC affichent des effets négatifs, suggérant que les périodes de sécheresse ou de faibles précipitations sont associées à des diminutions de Moy_ ZC025YR.

Les indicateurs T90_IAC et WP90_IAC ne montrent pas de significativité, impliquant une absence d'effet clair des températures élevées ou des précipitations intenses. Les tests de diagnostics révèlent des résidus non normalement distribués, posant des questions sur la fiabilité des estimations des coefficients. Pour améliorer la robustesse du modèle, il serait judicieux d'intégrer des variables additionnelles, d'appliquer des transformations pour corriger la non-normalité des résidus, ou d'explorer des modèles alternatifs tels que les modèles de volatilité pour traiter l'hétéroscédasticité observée. Ce modèle offre une base pour des analyses plus approfondies, bien que son ajustement et sa précision nécessitent des améliorations substantielles.

### **REGRESSIONS LINEAIRES AVEC LA VARIABLE DEPENDANTE: Moy_ ZC050YR**
"""

# Sélection des variables indépendantes et de la variable dépendante
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'
X_2 = data_mod[['IAC_CAN']]

X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC050YR'] #

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

"""Les résultats de la régression linéaire OLS pour la variable Moy_ ZC050YR montrent une capacité modeste du modèle à expliquer la variabilité de la variable dépendante avec un R-squared de 11.7% . Les coefficients pour les indicateurs saisonniers (hiver, été, printemps, automne) sont tous positifs et statistiquement significatifs, indiquant que chaque saison contribue positivement par rapport à la ligne de base non saisonnière. De manière intéressante, l'indice actuariel climatique (IAC_CAN) montre un effet négatif significatif, suggérant que des conditions climatiques mesurées par cet indice sont associées à une réduction de Moy_ ZC050YR. Les diagnostics indiquent que les résidus ne sont pas normalement distribués, ce qui peut affecter l'interprétation des résultats. La correction de cette non-normalité, potentiellement par des transformations ou des modèles plus complexes, pourrait améliorer la précision du modèle. L'amélioration du modèle pourrait également impliquer l'exploration d'autres facteurs externes qui pourraient influencer Moy_ ZC050YR, ou l'utilisation de modèles de volatilité pour gérer l'hétéroscédasticité apparente des résidus."""

# Sélection des variables indépendantes et de la variable dépendante Moy_ ZC075YR en tenant compte des composantes de IAC
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'

X_2 = data_mod[['T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC','S_IAC']]

X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC050YR'] #

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

"""### **REGRESSIONS LINEAIRES AVEC LA VARIABLE DEPENDANTE: Moy_ ZC075YR**"""

# Sélection des variables indépendantes et de la variable dépendante
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'
X_2 = data_mod[['IAC_CAN']]

X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC075YR'] #

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

# Sélection des variables indépendantes et de la variable dépendante Moy_ ZC075YR en tenant compte des composantes de IAC
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'

X_2 = data_mod[['T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC','S_IAC']]

X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC075YR'] #

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

"""### **REGRESSIONS LINEAIRES AVEC LA VARIABLE DEPENDANTE: Moy_ ZC100YR**"""

# Sélection des variables indépendantes et de la variable dépendante
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'
X_2 = data_mod[['IAC_CAN']]

X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC100YR'] #

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

# Sélection des variables indépendantes et de la variable dépendante Moy_ ZC100YR en tenant compte des composantes de IAC
X_1 = data_mod[['Saison_Hiver','Saison_Été', 'Saison_Printemps','Saison_Automne']].astype(int) # ajouter'T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC'

X_2 = data_mod[['T90_IAC', 'T10_IAC','P_IAC', 'D_IAC', 'WP90_IAC','S_IAC']]

X =pd.concat([X_1, X_2], axis=1)

y = data_mod['Moy_ ZC100YR'] #

# Ajout d'une constante à X pour inclure l'intercept
X = sm.add_constant(X)

# Création et ajustement du modèle de régression linéaire OLS
model = sm.OLS(y, X)
results = model.fit()

# Affichage du résumé des résultats du modèle
print(results.summary())

"""**# INTERPRETATION ET COMMENTAIRE: Choix de Moy_ ZC025YR pour la suite : meilleure R carré.mëme conclusion pour les autres. les mettre en annexe**

# **ANALYSE AVEC LE MODÈLE ARMA**
"""

print(data_mod.keys())

"""# **IDENTIFICATION DE L'ODRE DE AR ET MA**"""

# Vérification de la stationnarité de S&P_TSX_Der

result = adfuller(data['Moy_ ZC050YR'])
print('ADF Statistic:', result[0])
print('p-value:', result[1])

"""### La p-value est > 0.05 alors la série des prix de l'indice boursier n'est pas stationnaire, nous avons besoin de la différencier"""

# DIFFERENCTIATION

data['Moy_ ZC025YR_diff'] = data['Moy_ ZC025YR'].diff().dropna()

#Suppression des nan à nouveau
data=data.dropna()

# Identification des paramètres p et q : ici nous devons analyser le graohe des autocorrelation et des autocorrelations partielles

fig, axes = plt.subplots(1, 2, figsize=(15,4))
plot_acf(data['Moy_ ZC025YR_diff'].dropna(), ax=axes[0])
plot_pacf(data['Moy_ ZC025YR_diff'].dropna(), ax=axes[1], method='ywm')
plt.show()

"""**#Interpretations:**
Les graphiques d'autocorrélation (ACF) et d'autocorrélation partielle (PACF) présentés ici offrent des indications sur la structure temporelle des données de taux de rendement des obligations zero coupon que vous étudiez. Voici une analyse détaillée de ce que ces graphiques nous révèlent :

Autocorrélation (ACF): L'ACF montre une décroissance significative initiale suivie de valeurs qui s'atténuent rapidement vers zéro, ce qui est typique des séries qui ont été différenciées ou qui présentent une certaine forme de dépendance à court terme. Cela suggère que le modèle peut nécessiter une composante AR pour capter cette autocorrélation initiale.

Autocorrélation Partielle (PACF): La PACF montre un pic significatif au premier lag, puis les valeurs tombent rapidement vers zéro et restent dans la zone de non-significativité pour les lags suivants. Ce comportement est caractéristique d'un modèle potentiellement AR(1), où seulement le premier lag est pertinent pour prédire les valeurs futures de la série.

Recommandations pour la modélisation :
Modèle ARIMA: Étant donné le comportement observé dans l'ACF et le PACF, un modèle ARIMA(1,1,0) pourrait être approprié. Le premier terme AR aiderait à capter l'autocorrélation à court terme, et la différenciation première est déjà indiquée par la nature des données différenciées.

Vérification de la stationnarité: Il serait prudent de réaliser un test de stationnarité (comme le test ADF) pour confirmer que la série différenciée est bien stationnaire.

Validation du modèle: Après ajustement, il est crucial de vérifier les résidus du modèle ARIMA pour s'assurer qu'ils ressemblent à un bruit blanc, indiquant que le modèle a bien capturé toute l'information dans les données.

Ces analyses et ajustements vous aideront à mieux comprendre et prédire les comportements des taux de rendement, ce qui est essentiel pour la gestion de risque et la planification d'investissement dans des obligations zero coupon.
"""

plt.figure(figsize=(10, 5))
plt.plot(data['Moy_ ZC025YR_diff'], label='Moy_ ZC025YR_diff')
plt.title('Graphique de differentiation des taux de rendements des obligations zero coupon de maturité 3mois')
plt.xlabel('index')
plt.ylabel('Valeur')
plt.legend()
plt.grid(True)
plt.show()

"""# **Interpretation :**
Ce graphique montre la différenciation des taux de rendements des obligations zéro coupon de maturité 3 mois. La série temporelle affiche des fluctuations autour de zéro, mais des variations restent cependant notables, avec des pics significatifs qui suggèrent des réactions à des événements ou des annonces économiques spécifiques.

Analyse et suggestions pour la modélisation :
Stationnarité: Comme pour la série précédente, la différenciation semble aider à atteindre une stationnarité, essentielle pour les modèles ARIMA. Il serait prudent de confirmer cette stationnarité à l'aide de tests statistiques formels comme le test ADF.

Modélisation de la volatilité: Bien que moins extrême, la volatilité observée peut bénéficier de modèles de volatilité conditionnelle tels que GARCH pour mieux capturer les variations dans le temps et fournir des prévisions de volatilité plus précises.

Dépendance temporelle: L'analyse des autocorrélations devrait être entreprise pour déterminer l'ordre approprié des composants AR et MA dans un modèle ARIMA ou SARIMAX, en tenant compte des saisons si des cycles spécifiques sont observés à travers les données.

Validation de modèle: Une fois le modèle ajusté, il est crucial d'analyser les résidus pour vérifier qu'ils ne montrent aucune structure systématique (c'est-à-dire qu'ils sont proches du bruit blanc), ce qui indiquerait que le modèle capture bien la dynamique de la série.

Comparaison inter-séries: Comparer les comportements de différentes séries de maturités pourrait également révéler des insights intéressants sur la manière dont les attentes du marché varient avec la durée jusqu'à la maturité des obligations.

Cette analyse contribue à une compréhension plus complète des mouvements de taux sur le marché des obligations zéro coupon et aide à formuler des stratégies de gestion de portefeuille basées sur des prévisions de taux plus informées.

"""

# CONSTRUCTION DU MODELE ARMAX AVEC ORDRE DE DIFFERENCIATION 0


from statsmodels.tsa.statespace.sarimax import SARIMAX

model = SARIMAX(data['Moy_ ZC025YR_diff'],exog=data['IAC_CAN'],
                order=(2, 0, 1),  # (p, d, q) où p est l'ordre AR, d est l'ordre de différenciation, q l'ordre MA
                enforce_stationarity=False,enforce_invertibility=False)

# Ajustement du modèle
results = model.fit()

# Affichage du résumé du modèle
print(results.summary())

# Analyses des résidus .
results.plot_diagnostics(figsize=(15, 12))
plt.show()

"""### **COMMENTAIRES ET INTERPRETATIONS DES STATISTIQUES :**

Les résultats du modèle SARIMAX(2,0,1) appliqué à la série des taux de rendement des obligations zero coupon montrent certains points intéressants et des zones potentielles de préoccupation :

Paramètres AR et MA : Le modèle inclut deux termes autorégressifs (AR) et un terme de moyenne mobile (MA). Les coefficients pour ar.L1 et ar.L2 sont significatifs, indiquant que les valeurs passées influencent directement les valeurs actuelles, avec des p-values bien en dessous de 0.05. En revanche, le terme ma.L1 a un coefficient extrêmement élevé (5.0675), ce qui est inhabituel et pourrait indiquer un problème de spécification ou de convergence du modèle.

Insignifiance de IAC_CAN : Le coefficient pour IAC_CAN est proche de zéro (0.0003) et n'est pas statistiquement significatif (p-value de 0.309), ce qui suggère que cette variable explicative n'a pas d'impact significatif sur les variations des taux de rendement dans ce modèle.

Diagnostiques des résidus :

Ljung-Box test : Le test indique une p-value de 0.88, suggérant que les résidus du modèle n'ont pas d'autocorrélation significative à un lag spécifique, ce qui est un bon signe d'adéquation du modèle.
Test de Jarque-Bera : Avec une p-value de 0.00, ce test indique que les résidus ne suivent pas une distribution normale, ce qui est préoccupant pour les hypothèses classiques de la régression OLS.
Hétéroscédasticité : Le test indique une hétéroscédasticité significative (p-value de 0.00), avec une valeur très faible pour le rapport de hétéroscédasticité, indiquant une variation inégale des résidus à travers le temps.

### **CONCLUSION ET RECOMMANDATIONS :**
Bien que le modèle capte certains aspects des dynamiques temporelles des taux de rendement, les problèmes de non-normalité des résidus et d'hétéroscédasticité soulèvent des questions sur l'adéquation globale du modèle. Il serait bénéfique de :

Revoir les spécifications du modèle, peut-être en explorant des transformations des variables ou l'ajout d'autres termes explicatifs.
Considérer l'utilisation de modèles robustes aux anomalies de distribution des résidus, tels que les modèles avec des erreurs GARCH ou EGARCH.
Continuer à surveiller la performance du modèle avec de nouvelles données pour ajuster et améliorer le modèle au fil du temps.

### **COMMENTAIRES ET INTERPRETATIONS DES GRAPHIQUES :**


**Le graphique des Résidus Standardisés** montrent des pics significatifs, indiquant des écarts par rapport à la moyenne qui ne sont pas capturés par le modèle. Cette variabilité excessive peut être le signe de chocs ou de variations non pris en compte dans le modèle actuel.

**L'histogramme des résidus** montre que les résidus ne suivent pas une distribution normale, comme le montre également l'ajustement de la courbe de densité (KDE) par rapport à la ligne de la distribution normale (N(0,1)). Cela indique des problèmes de normalité avec des queues lourdes et potentiellement des données asymétriques.


 **Le graphique Q-Q**  montre une déviation notable des quantiles théoriques par rapport aux quantiles de l'échantillon, surtout dans les extrémités de la distribution, suggérant la présence de valeurs extrêmes ou d'outliers. Cela remet en question l'adéquation de la distribution normale pour ces résidus.


 **Le correlogramme** révèle que l'autocorrélation pour les premiers décalages est significativement élevée, ce qui pourrait indiquer que le modèle n'a pas entièrement capturé la dynamique temporelle des données. Les décalages subséquents semblent tomber dans la bande de non-significativité, ce qui est un signe positif de l'efficacité du modèle à ces décalages.

 Les diagnostics indiquent que le modèle SARIMAX pourrait nécessiter des ajustements pour améliorer sa spécification. L'absence de normalité et la présence d'autocorrélations résiduelles suggèrent que d'autres transformations des données ou l'ajout de composants supplémentaires comme un modèle GARCH pour les variances conditionnelles pourraient être nécessaires. L'ajustement pour mieux gérer les valeurs aberrantes et les périodes de volatilité accrue pourrait également améliorer les performances du modèle. Ces ajustements aideront à obtenir des prévisions plus précises et à mieux comprendre les dynamiques sous-jacentes des taux de rendement observés.

**Les diagnostics indiquent que le modèle SARIMAX pourrait nécessiter des ajustements pour améliorer sa spécification. L'absence de normalité et la présence d'autocorrélations résiduelles suggèrent que d'autres transformations des données ou l'ajout de composants supplémentaires comme un modèle GARCH pour les variances conditionnelles pourraient être nécessaires. L'ajustement pour mieux gérer les valeurs aberrantes et les périodes de volatilité accrue pourrait également améliorer les performances du modèle. Ces ajustements aideront à obtenir des prévisions plus précises et à mieux comprendre les dynamiques sous-jacentes des taux de rendement observés.**

# **QUELQUES AMÉLIORATIONS DU MODÈLE ARMA PRECEDENT**



### *   **Examen de la stabilité des paramètres dans le temps.**
"""

# l'examen de la stabilité des paramètres dans le temps.
# Affichage des résidus
plt.figure(figsize=(12, 6))
plt.plot(results.resid, label='Résidus')
plt.title('Résidus du modèle SARIMAX')
plt.legend()
plt.show()

"""### Les résidus du modèle SARIMAX, tels qu'ils apparaissent sur le graphique, montrent une fluctuation autour de zéro, indiquant qu'il n'y a pas de biais systématique significatif dans les prédictions du modèle. La plupart des résidus semblent être contenus dans une bande étroite, ce qui est un bon signe de la capacité du modèle à capturer une grande partie de l'information dans les données. Cependant, les pics sporadiques, notamment les excursions plus grandes que les autres observées, pourraient indiquer des anomalies ou des chocs externes que le modèle actuel ne parvient pas à capturer pleinement.
###Ces pics pourraient signaler la présence de volatilité non expliquée, ce qui pourrait être une indication pour examiner plus en détail les modèles de volatilité conditionnelle comme GARCH, ou pour intégrer des variables explicatives supplémentaires qui pourraient expliquer ces variations. En outre, il pourrait être utile de tester la stationnarité des résidus pour s'assurer qu'il ne reste pas de tendances ou de cycles non capturés par le modèle actuel. Un examen plus approfondi des périodes correspondant aux grands résidus pourrait également révéler des dynamiques spécifiques ou des événements qui nécessitent un ajustement du modèle ou une modélisation séparée.
"""

# Affichage de la variance roulante des résidus pour voir la stabilité de la variance
rolling_var = results.resid.rolling(window=12).var()
plt.figure(figsize=(15, 6))
plt.plot(rolling_var, label='Variance roulante des résidus')
plt.title('Variance roulante des résidus')
plt.legend()
plt.show()

"""La variance roulante des résidus illustre des périodes de volatilité variable dans les données analysées. La présence de pics significatifs à certains points suggère des épisodes où les variations des taux de rendements des obligations sont plus imprévisibles et pourraient signaler des événements externes ou des changements dans les dynamiques du marché non capturés par le modèle SARIMAX actuel.

Ces variations accentuées de la variance indiquent que le modèle pourrait bénéficier de l'intégration d'un modèle GARCH pour modéliser et prévoir cette volatilité conditionnelle. De telles améliorations permettraient de mieux comprendre et anticiper les périodes de turbulences sur le marché, offrant ainsi une modélisation plus robuste et des prédictions améliorées pour la gestion du risque et la prise de décision stratégique en finance.
"""

#TEST DE WHITE
from statsmodels.stats.diagnostic import het_white

# Préparer les données pour le test de White
residus = results.resid
exog = data[['IAC_CAN']]  # Utilisez les mêmes variables exogènes que dans votre modèle
exog_const = sm.add_constant(exog)  # Ajouter une constante aux variables explicatives pour le test

# Effectuer le test de White sur les résidus
test_stat, p_value, f_stat, f_p_value = het_white(residus, exog_const)

# Afficher les résultats du test de White
print("Statistique du test de White:", test_stat)
print("P-value du test de White:", p_value)
print("Statistique F:", f_stat)
print("P-value du F-test:", f_p_value)

"""### ***Avec ces valeurs de p-value la présence d'hétéroscédasticité dans les résidus est confirmée et signifie que les estimations standards des erreurs des coefficients du modèle sont biaisées, ce qui peut mener à des conclusions erronées concernant la significativité des variables du modèle.***

En effet

Les résultats du test de White indiquent une présence significative d'hétéroscédasticité dans les résidus du modèle analysé. La statistique du test est de 7.944 avec une p-value de 0.0188, et la statistique F est de 4.017 avec une p-value de 0.0187. Ces valeurs suggèrent que les variations de la variance des erreurs ne sont pas aléatoires mais plutôt liées à des variables ou des structures non capturées dans le modèle actuel.

Cela pourrait signaler que certains facteurs explicatifs ou dynamiques de série temporelle influencent la variance de façon systématique, rendant nécessaire l'ajustement du modèle initial ou l'adoption de modèles plus complexes comme les modèles GARCH pour traiter la volatilité conditionnelle, ou encore la révision des variables explicatives pour mieux modéliser la variation des données et améliorer la robustesse des prédictions.

"""

#TEST  de Breusch-Pagan

from statsmodels.stats.diagnostic import het_breuschpagan

# Variables exogènes utilisées dans le modèle
# Nous devons inclure une constante dans les variables exogènes pour le test
exog = sm.add_constant(data[['IAC_CAN']])

# Effectuer le test de Breusch-Pagan
bp_test = het_breuschpagan(residus, exog)

# Afficher les résultats du test de Breusch-Pagan
bp_stat, bp_pvalue, fvalue, fpvalue = bp_test
print("Statistique de Breusch-Pagan :", bp_stat)
print("P-value de Breusch-Pagan :", bp_pvalue)
print("Statistique F :", fvalue)
print("P-value du F-test :", fpvalue)

"""### ***Les résultats du test de Breusch-Pagan confirment la présence d'hétéroscédasticité dans les résidus de notre modèle, suggérant la nécessité de réviser le modèle ou d'adopter des techniques qui prennent en compte cette variance non constante pour améliorer la précision et la validité des analyses.***"""

# CONSTRUCTION DU MODELE ARIMA ARMAX AVEC ORDRE DE DIFFERENCIATION 1
from statsmodels.tsa.statespace.sarimax import SARIMAX

model_2 = SARIMAX(data['Moy_ ZC025YR_diff'],
                exog=data['IAC_CAN'],
                order=(2, 1, 1),  # (p, d, q) où p est l'ordre AR, d est l'ordre de différenciation, q l'ordre MA
                enforce_stationarity=False,
                enforce_invertibility=False)

# Ajuster le modèle
results_2 = model_2.fit()

# Afficher le résumé du modèle
print(results_2.summary())

# Diagnostics pour vérifier les résidus etc.
results_2.plot_diagnostics(figsize=(15, 12))
plt.show()

"""### ***Le modèle SARIMAX(1, 1, 1) presente des conclusions moindres que le modèle SARIMAX(1, 0, 1)***


"""

pip install arch

## MODELE GARCHE POUR RESIDU DE SARIMX(2,0,1)

from arch import arch_model

# Création du modèle GARCH
garch = arch_model(residus, p=1, q=1)  # Modèle GARCH(1,1)
results_garch = garch.fit(update_freq=3)
print(results_garch.summary())

"""## **INTERPRESTATION ET COMMENTAIRE :**

Les résultats du modèle GARCH(1,1) pour la série analysée montrent que la constante moyenne (mu) est extrêmement précise avec une valeur de **0.2099**, présentant une très faible erreur standard et une t-value extrêmement élevée, ce qui suggère une forte stabilité de cette estimation à travers le modèle. Toutefois, les paramètres du modèle de volatilité, **alpha[1]** et **beta[1]**, montrent des incertitudes significatives avec des valeurs t et des intervalles de confiance qui ne permettent pas d'affirmer leur significativité statistique.

**Alpha**, avec une valeur de **0.100** et une p-value de **0.761**, et beta, avec une valeur de **0.880** et une p-value de **0.116**, ne sont pas statistiquement significatifs, ce qui met en question la capacité du modèle à capturer efficacement la dynamique de la volatilité des données. Cela peut indiquer que le modèle pourrait nécessiter une révision des paramètres ou l'utilisation d'autres formes de modèles de volatilité qui pourraient mieux s'adapter aux caractéristiques des données observées.

Pour améliorer la modélisation, il pourrait être judicieux d'explorer des modèles avec différentes spécifications de volatilité, tels que EGARCH ou GARCH avec des distributions autres que la normale, ou d'augmenter le nombre de lags dans les composantes alpha et beta pour voir si une structure plus complexe pourrait mieux capturer les dynamiques observées.

"""

## MODELE GARCHE POUR RESIDU DE SARIMX(2,1,1)

from arch import arch_model
residus_2 = results_2.resid
# Création du modèle GARCH
garch_2 = arch_model(residus_2, p=1, q=1)  # Modèle GARCH(1,1)
results_garch_2 = garch_2.fit(update_freq=3)
print(results_garch_2.summary())

"""### **Les conclusions de GARCH(1,1) sur les residus de SARIMAX(2,0,1) sont identiques, voire meilleurs que celui de  de GARCH(1,1) sur les residus de SARIMAX(2,1,1)**"""

# Création du modèle EGARCH avec distribution normale
egarch_model = arch_model(residus, vol='EGARCH', p=1, q=1)

egarch_results = egarch_model.fit(update_freq=3)
print(egarch_results.summary())

"""## **INTERPRESTATION ET COMMENTAIRE :**

Les résultats du modèle **EGARCH(1,1)** présentent des estimations statistiquement significatives pour le terme moyen **μ** et les paramètres de volatilité **α[1]** et **β[1]**. Le terme **μ**, avec une valeur exceptionnellement précise de **8.2762**, est significatif, indiquant une contribution constante à la série temporelle. L'omega négatif à **-2.9009** suggère une réactivité inverse entre la volatilité et les innovations précédentes, typique des modèles **EGARCH** où la volatilité peut être influencée asymétriquement par les chocs passés.

Le paramètre **α[1]**, significatif, montre l'impact des chocs précédents sur la volatilité actuelle, tandis que le **β[1]** très élevé et significatif indique une persistance élevée de la volatilité. Ces résultats suggèrent que le modèle capte bien les dynamiques de la volatilité, mais l'extrême magnitude des valeurs log-likelihood et AIC indique potentiellement des problèmes de modélisation ou d'échelle des données qui pourraient nécessiter un ajustement ou une validation supplémentaire pour s'assurer de la robustesse du modèle EGARCH utilisé.





**Le modèle EGARCH ajusté avec la distribution de normale fournit une analyse robuste de la volatilité, en capturant efficacement la nature des extrêmes et en offrant une bonne compréhension de la persistance et de la réactivité de la volatilité. La non-significativité de certains paramètres suggère d'autres investigations ou ajustements.**
"""

# Création du modèle EGARCH avec distribution de student

egarch_model = arch_model(residus, vol='EGARCH', p=1, q=1,dist='t')

egarch_results = egarch_model.fit(update_freq=3)
print(egarch_results.summary())

"""## **INTERPRESTATION ET COMMENTAIRE :**

Les résultats du modèle EGARCH ajusté avec une distribution des erreurs de Student montrent une précision remarquable pour l'estimation du terme moyen
𝜇, indiquant une influence constante notable sur la série temporelle. Cependant, les paramètres de volatilité révèlent des anomalies dans les estimations: l'omega affiche une valeur négative non significative, ce qui est habituel pour un modèle EGARCH indiquant que les chocs négatifs affectent plus la volatilité que les chocs positifs, mais sa non-significativité suggère une faible influence.

L'alpha, bien que présentant un effet extrêmement grand et significatif, est probablement un artefact numérique dû à des problèmes de convergence ou d'échelle des données. Le beta à zéro et non significatif indique une absence de persistance dans les effets des chocs précédents sur la volatilité future, ce qui est inhabituel et suggère des problèmes sous-jacents dans la spécification du modèle ou des données.

Le paramètre de degrés de liberté 𝜈 pour la distribution de Student est non significatif, suggérant que l'ajout de cette distribution n'améliore pas significativement la modélisation des queues de distribution par rapport à une distribution normale. Ce modèle nécessite une réévaluation et potentiellement une reformulation pour assurer une modélisation robuste et interprétable de la volatilité des rendements observés.
"""